title: Mirko Brombin
description: 
author: Mirko brombin
email: mirko@bromb.in

assets: /assets
uploads: /uploads

permalink: /blog/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

default_lang: en
languages:
  - code: en
    name: English
  - code: es
    name: Español
  - code: it
    name: Italiano

navigation:
  - link: "/"
    name: nav.me
  - link: "/blog/"
    name: nav.blog
  - link: "/support/"
    name: nav.support
  - link: "https://github.com/mirkobrombin"
    name: nav.projects
  - link: "https://t.me/mirkofeeds"
    name: nav.feed

