navItems:
  main:
    - name: "HOME"
      href: "/"
      key: "home"
  secondary:
    - name: "STORIES"
      href: "/stories"
      key: "stories"
    - name: "CINEMA"
      href: "/cinema"
      key: "cinema"
    - name: "TRAVELS"
      href: "/travels"
      key: "travels"
    - name: "FOOD & DRINKS"
      href: "/food-drinks"
      key: "food-drinks"
  tertiary:
    - name: "BOOKS"
      href: "/books"
      key: "books"
    - name: "WORK"
      href: "/work"
      key: "work"

socialLinks:
  - name: "simple-icons:facebook"
    href: "#"
  - name: "simple-icons:youtube"
    href: "#"
  - name: "simple-icons:twitter"
    href: "#"
  - name: "simple-icons:instagram"
    href: "#"

footerLinks:
  - "ABOUT"
  - "CONTACT US"
